<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
      <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DomainUserService\DomainUserService.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentMigrator" />
      <PackageReference Include="FluentMigrator.Runner" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="Npgsql" />
    </ItemGroup>

</Project>
